'use client';
// src/components/ai/AISummaryButton.tsx
// Button that triggers AI summarization of a post.
// Checks for a cached summary (Post.aiSummary) first before calling OpenAI.

import { useState } from 'react';
import { Sparkles, X, Loader2 } from 'lucide-react';
import toast from 'react-hot-toast';

interface Props {
  postId: string;
  cachedSummary: string | null;
  title: string;
}

export default function AISummaryButton({ postId, cachedSummary, title }: Props) {
  const [open, setOpen] = useState(false);
  const [summary, setSummary] = useState<string | null>(cachedSummary);
  const [loading, setLoading] = useState(false);

  const handleOpen = async () => {
    setOpen(true);
    if (summary) return; // Use cached

    setLoading(true);
    try {
      const res = await fetch(`/api/posts/${postId}/summarize`, { method: 'POST' });
      if (!res.ok) throw new Error('Failed to generate summary');
      const data = await res.json();
      setSummary(data.summary);
    } catch {
      toast.error('Could not generate summary');
      setOpen(false);
    } finally {
      setLoading(false);
    }
  };

  return (
    <>
      <button
        onClick={handleOpen}
        className="flex items-center gap-1.5 px-3 py-1.5 text-sm font-sans border border-[var(--border)] text-[var(--text-muted)] hover:border-[var(--accent)] hover:text-[var(--accent)] transition-colors rounded-sm"
      >
        <Sparkles size={14} />
        AI Summary
      </button>

      {open && (
        <div className="fixed inset-0 z-50 flex items-center justify-center p-4" role="dialog" aria-modal="true" aria-label="AI Summary">
          {/* Backdrop */}
          <div className="absolute inset-0 bg-black/40 backdrop-blur-sm" onClick={() => setOpen(false)} />

          {/* Modal */}
          <div className="relative bg-[var(--bg-primary)] border border-[var(--border)] rounded-sm shadow-card max-w-lg w-full p-8 animate-slide-up">
            <button
              onClick={() => setOpen(false)}
              className="absolute top-4 right-4 text-[var(--text-faint)] hover:text-[var(--text-primary)] transition-colors"
              aria-label="Close"
            >
              <X size={18} />
            </button>

            <div className="flex items-center gap-2 mb-6">
              <Sparkles size={18} className="text-[var(--accent)]" />
              <h3 className="text-sm font-sans font-medium uppercase tracking-widest text-[var(--text-faint)]">
                AI Summary
              </h3>
            </div>

            <h4
              className="text-xl font-bold text-[var(--text-primary)] mb-4"
              style={{ fontFamily: 'var(--font-cormorant)' }}
            >
              {title}
            </h4>

            {loading ? (
              <div className="flex items-center gap-3 text-[var(--text-muted)] py-6">
                <Loader2 size={18} className="animate-spin" />
                <span className="text-sm font-sans italic">Logos is reading…</span>
              </div>
            ) : (
              <p className="text-[var(--text-secondary)] leading-relaxed" style={{ fontFamily: 'var(--font-lora)' }}>
                {summary}
              </p>
            )}

            <p className="text-xs font-sans text-[var(--text-faint)] mt-6 pt-4 border-t border-[var(--border)]">
              Generated by Logos (GPT-4o) · Summaries may not capture every nuance.
            </p>
          </div>
        </div>
      )}
    </>
  );
}
